var crossingData = {"type":"FeatureCollection","features":[
{"type":"Feature","id":"1","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.393346, 33.761381]}},
{"type":"Feature","id":"2","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.493346, 33.761381]}},
{"type":"Feature","id":"3","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.593346, 33.761381]}},
{"type":"Feature","id":"4","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.693346, 33.761381]}},
{"type":"Feature","id":"5","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.793346, 33.761381]}},
{"type":"Feature","id":"6","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.393346, 33.861381]}},
{"type":"Feature","id":"7","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.393346, 33.961381]}},
{"type":"Feature","id":"8","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.393346, 33.361381]}},
{"type":"Feature","id":"9","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.393346, 33.461381]}},
{"type":"Feature","id":"10","properties":{"name":"Rail Crossing/Intersection","number":34, "incidents":"incident 1 <br />incident 2 <br />incident 3"},"geometry":{"type":"Point","coordinates":[-84.393346, 33.561381]}}
]};